### ISSUE TITLE
[LikeLion 11th Assignment] 4일차 - Django Model (1)

### ISSUE THREAD

**Issue by mumat0103** [LIKELION-KMU-11TH/Assignment#3]
# 4일차 세션 과제 : Blog 클래스에 필드 추가해보기
<hr/>

## 필수 과제

1. 실습 때 만든 Blog 클래스에 본인이 필요하다고 생각하는 필드 추가하기 (1개 이상)
2. Admin 페이지에서 모델 객체 생성, 조회, 수정, 삭제 해보기

<hr/>

## 기타 요구사항

- 요구사항 1 : CRUD 세션에서도 사용할 예정이니 _**꼭 반드시**_ 과제 해주시길 바랍니다.
- 요구사항 2 : 깃 레포 하나 파셔서 업로드 하시는 것을 추천드립니다.
<hr/>

## 과제 제출 형식
1. 이름
2. models.py에 작성한 코드
3. 어드민 페이지 스크린샷 (모델 객체 생성 후 스샷 찍어주시면 됩니다.)
4. 깃허브 레포 주소
<hr/>

## 마감일
- 3월 27일 (월) 18:00까지

**Comment by mumat0103** [comment]
예시)
1. 천성규
2. 
```
class Blog(models.Model):
    title = models.CharField(max_length=50)
    subtitle = models.TextField(max_length=150)
    author = models.CharField(max_length=6)
```

3. 
![image](https://user-images.githubusercontent.com/69793985/226581300-ad102e15-cdf1-4b25-ac59-095e37abb040.png)

**Comment by haram8009** [comment]
1. 이하람
2.   
```python
class Blog(models.Model):
    # objects = models.Manager()
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    body = models.TextField(default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to=image_upload_path , null=True)

    def __str__(self):
        return str(self.title)
```
3. 
![image](https://user-images.githubusercontent.com/84117653/227297832-d82a4800-a876-48b0-834e-f60fc8ac3c29.png)
![image](https://user-images.githubusercontent.com/84117653/227300040-184bc2e1-3efb-458e-8697-ea9270a78a4c.png)

4. https://github.com/haram8009/legendary-journey

**Comment by minjeoong** [comment]
1. 김민정
2.
`class Blog(models.Model):
    title = models.CharField(max_length=100, help_text='블로그 제목을 작성해주세요.')
    created_at = models.DateTimeField(auto_now_add=True)
    
    Studend_id = [
        ('17', '17학번'),('18', '18학번'),('19', '19학번'),('20', '20학번'), ('22','21학번'), ('23','23학번')
    ]
    StudentID = models.CharField(max_length=2, choices=Studend_id, default ='')
    Email = models.EmailField(max_length=200)
    introduce = models.TextField()
    def __str__(self):
        return self.title`
3.
<img width="1552" alt="스크린샷 2023-03-24 18 13 29" src="https://user-images.githubusercontent.com/88662427/227476174-b825ae71-84bc-413f-807a-1413c98e483f.png">

4. https://github.com/minjeoong/Django_2.git

**Comment by eraser502** [comment]
1. 김도훈
2. class Blog(models.Model):
    title = models.CharField(max_length=100)
    created_at = models.DateField(auto_now_add=True)
    contents = models.TextField()
    author = models.CharField(max_length=10)
    image = models.ImageField(upload_to="blog/%Y/%m/%d")

    def __str__(self):
        ret
3. ![스크린샷 2023-03-26 오전 1 04 15](https://user-images.githubusercontent.com/87667113/227729351-8186070c-26ce-4408-a465-88f53105caf5.png)
![스크린샷 2023-03-26 오전 1 04 23](https://user-images.githubusercontent.com/87667113/227729354-ae0bb61b-7cac-4331-9637-8e283e6994fd.png)
urn self.title
4. https://github.com/eraser502/Django_Model_1

**Comment by imjanghyeok** [comment]
1. 임장혁
2. class Blog(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=10,default="")
    created_at = models.DateTimeField(auto_now_add=True)
    introduce = models.TextField()
    sns_id = models.URLField(max_length=200)
    age_list = []
    for i in range(0,100):
        age_list.append((i, 1930+i))
    age = models.IntegerField(choices=age_list, default="0")
    email = models.EmailField(max_length=30)
    modify_date = models.DateField(auto_now=True)

    def __str__(self):
        return self.title
3.
![1](https://user-images.githubusercontent.com/66295199/227732660-0d999234-0ea0-436d-b0d5-24a82bf24a6d.png)
![2](https://user-images.githubusercontent.com/66295199/227732663-a9cfb55a-03ca-42c5-b792-da066d5a49db.png)
4. https://github.com/imjanghyeok/sessionmodel

**Comment by goldjh93** [comment]
1.이지형
2.

class Blog(models.Model):
    LANGUAGE_ENGLISH='en'
    LANGUAGE_KOREAN='kr'
    title =models.CharField(max_length=100)
    created_at= models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=100, default='')
    LANGUAGE_CHOICE=((LANGUAGE_ENGLISH,'English'),(LANGUAGE_KOREAN,'Korean'))
    language = models.CharField(max_length=2, choices=LANGUAGE_CHOICE, blank=True, 
    default=LANGUAGE_ENGLISH)
    introduce = models.TextField()
    birthday= models.DateField(default='2000-01-01')
    email= models.EmailField(max_length=100, blank=True, default='')
    picture= models.ImageField(upload_to='blog_pics', blank=True) 



    def __str__(self) :
        return self.title
    

3.
<img width="1469" alt="스크린샷 2023-03-26 오후 1 35 29" src="https://user-images.githubusercontent.com/107250637/227755898-b0e3cdba-9243-4de8-aced-b4556cf22b84.png">
<img width="1469" alt="스크린샷 2023-03-26 오후 1 36 19" src="https://user-images.githubusercontent.com/107250637/227755900-7b75c705-a6fb-4463-9b57-35fd3b608a8e.png">



4. https://github.com/goldjh93/Django1

**Comment by Leekm01** [comment]
1. 이경민
2. `from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=100, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    introduce = models.TextField(null=True)
    email = models.EmailField(max_length=128, null=True)
    sns = models.URLField(null=True)


    def __str__(self):
        return self.title`
3. 
<img width="960" alt="실행화면" src="https://user-images.githubusercontent.com/75059690/227766867-328c3869-d4ac-41ba-90fa-3be02648e922.png">
<img width="960" alt="실행화면1" src="https://user-images.githubusercontent.com/75059690/227766868-c38a9b8e-c424-4c6c-a4fa-cd3659aeea79.png">

4. https://github.com/Leekm01/mission3

**Comment by tmdtmdqorekf** [comment]
1. 김승언

2. `from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    introduce = models.TextField()
    hobby = models.TextField()

    def __str__(self):
        return self.title`

3. 
![과제2](https://user-images.githubusercontent.com/119438312/227767441-52204adf-4257-4d6e-879c-845456118c7f.JPG)

4. https://github.com/tmdtmdqorekf/likelions-assignment

**Comment by yun-seul** [comment]
1. 윤영돈
2.  from django.db import models

# Create your models here.
class Blog(models. Model):
    title = models.CharField(max_length=50)
    subtitle = models.TextField(max_length=150)
    author = models.CharField(max_length=5)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    introduce = models.TextField()

    
def __str__(self):
    return self.title

3. 
![image](https://user-images.githubusercontent.com/127651725/227771326-9574794d-36a5-4699-9f80-7c64afe648fb.png)

4. https://github.com/yun-seul/session4

**Comment by kym8821** [comment]
1. 김용민
2. ```python
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    problem_number = models.IntegerField(default=1000)
    problem_text = models.TextField()
    
    def __str__(self):
        return self.title
``` 
3. 
![image](https://user-images.githubusercontent.com/127489230/227778457-2b786a90-9c3b-48cd-a129-0f085bb37402.png)

4. https://github.com/kym8821/likelion_django_model1.git

**Comment by Leekm01** [comment]
1. 이경민
2. 
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=100, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    introduce = models.TextField(null=True)
    email = models.EmailField(max_length=128, null=True)
    sns = models.URLField(null=True)


    def __str__(self):
        return self.title

3. 
<img width="960" alt="실행화면" src="https://user-images.githubusercontent.com/75059690/227781178-262c39d8-d689-47ad-a63d-e55bce50e473.png">
<img width="960" alt="실행화면1" src="https://user-images.githubusercontent.com/75059690/227781182-4c2f5638-94b0-4a64-a7eb-abbaca5e2476.png">

4.

**Comment by Yun-hongki** [comment]
1. 윤홍기
2. class Blog(models.Model):
    title = models.CharField(max_length=100, null=True)
    author = models.CharField(max_length=20, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    introduce = models.TextField()
    Email = models.EmailField(max_length=100, blank=True)
    image = models.ImageField(upload_to='blog_img', blank=True)

    def __str__(self):
        return self.title

3.
<img width="958" alt="사진" src="https://user-images.githubusercontent.com/84968311/227786490-3b4c01ad-40af-4a84-b82f-07dbfa8f57d3.png">

4.https://github.com/Yun-hongki/Django-model-1-

**Comment by LyuDevz** [comment]
1. 류상준
2. `from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=100, help_text='블로그 제목을 작성해주세요')
    author = models.CharField(max_length=10,default="")
    StudentID = models.CharField(max_length=8,default="", help_text="학번을 입력해주세요(예시:20181020)")
    email = models.EmailField(max_length=128, null=True)
    posted_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    introduce = models.TextField()
    
   
    def __str__(self):
        return self.title`
3. 
<img width="1680" alt="Screenshot 2023-03-27 at 1 02 39 AM" src="https://user-images.githubusercontent.com/123153302/227788372-b2e8f8d8-4fcf-4cc7-b2de-3fb7df8e0951.png">
<img width="1676" alt="Screenshot 2023-03-27 at 1 01 47 AM" src="https://user-images.githubusercontent.com/123153302/227788377-acae2568-835e-4957-84e6-bdddb803bc72.png">
4. https://github.com/LyuDevz/Django_Model_1

**Comment by chanjin1998** [comment]
1. 정찬진
2. 
  ```
class Blog(models.Model):
  title = models.CharField(max_length=100)
  created_at = models.DateTimeField(auto_now_add=True)
  introduce = models.TextField()
  email = models.EmailField(max_length=100, null=True)
  upload = models.FileField(upload_to='uploads/',null=True)

  def __str__(self):
    return self.title
```
3.
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/70675133/227792534-d7ca8241-c353-4e8b-a2e1-a360dae87ac3.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/70675133/227792567-55a855ae-f7d1-4106-b330-1a45022cefee.png">

**Comment by SYunje** [comment]
1. 신윤제
2. class Blog(models.Model):
    title = models.CharField(max_length=100)
    email = models.EmailField(max_length=50)
    author = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_created=True)
    introduce = models.TextField()

    def __str__(self):
        return self.title

3.
![image](https://user-images.githubusercontent.com/1
![image](https://user-images.githubusercontent.com/118589494/227799442-f0b19123-04e0-4dda-bc09-dfba55db5512.png)
18589494/227799428-2253b5ff-1627-4e7e-84a3-90258e7be804.png)

4.https://github.com/SYunje/session4

**Comment by gpffh20** [comment]
1. 신은영
2. 
``` python
class Blog(models.Model):
    title = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    introduce = models.TextField()
    author = models.CharField(max_length=6, default="")
    upload = models.FileField(upload_to='blog/uploads/', null=True)
```
3. 
<img width="1717" alt="image" src="https://user-images.githubusercontent.com/111725249/227817768-9281ec2a-eae1-486b-a3e6-f1511ee26b2d.png">
4. https://github.com/gpffh20/like_lion_blog

**Comment by Kim-Yul** [comment]
1. 김유림
2.
class Blog(models.Model):
    title = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    studentID = models.IntegerField(default=0)
    writer = models.CharField(max_length=10, default="")
    introduce = models.TextField()

    def __str__(self):
        return self.title

3. 
![image](https://user-images.githubusercontent.com/65997015/227817538-cff6f7c5-7075-445d-b50a-9afdca473331.png)

4. https://github.com/Kim-Yul/session_0323

**Comment by Won-yeji** [comment]
1. 원예지
2.
``` python
class Blog(models.Model):
  title = models.CharField('제목', max_length=100)
  position_choices = [
    ('선택', 'None'), ('남자', '남자'), ('여자', '여자')
  ]
  position = models.CharField('성별', max_length=10, choices = position_choices, default='선택')
  introduce = models.TextField('내용')
  birthdate = models.DateField('생일', null=True)

  def __str__(self):
    return self.title
```
3.
![3](https://user-images.githubusercontent.com/124643604/227829730-c3a61372-85cf-4218-9a47-e5fbe982d5d2.PNG)
![2](https://user-images.githubusercontent.com/124643604/227829738-db625003-bc6f-4148-b2f2-0551e88f7e3b.PNG)
4. https://github.com/Won-yeji/likelion-djangomodel

**Comment by KRimwoo** [comment]
1. 김우림
2. `class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Blog(models.Model):
    title = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    introduce = models.TextField()
    image = models.ImageField(upload_to="post_image/", blank=True)
    
    def __str__(self):
        return self.title`
3.
<img width="843" alt="스크린샷 2023-03-27 오후 2 22 22" src="https://user-images.githubusercontent.com/66295173/227848091-97d1adcb-289a-4163-a6a0-41e9485e8b39.png">
<img width="829" alt="스크린샷 2023-03-27 오후 2 22 44" src="https://user-images.githubusercontent.com/66295173/227848122-85383e82-c41e-438f-ae43-4d14ff7fdf8d.png">

4. https://github.com/KRimwoo/Session_4_django_model

**Comment by KRimwoo** [comment]
1. 김우림
```
class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Blog(models.Model):
    title = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    introduce = models.TextField()
    image = models.ImageField(upload_to="post_image/", blank=True)
    
    def __str__(self):
        return self.title
```

3. 
<img width="843" alt="스크린샷 2023-03-27 오후 2 22 22" src="https://user-images.githubusercontent.com/66295173/227859114-6137dff9-43a0-4af5-8304-022dcbd9f89e.png">
<img width="829" alt="스크린샷 2023-03-27 오후 2 22 44" src="https://user-images.githubusercontent.com/66295173/227859122-3cd8763e-2117-4c2e-94c0-bb694559cd3e.png">

4. https://github.com/KRimwoo/Session_4_django_model

**Comment by anj1nkyu** [comment]
1. 안진규
2. from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    introduce = models.TextField() 
    content = models.TextField()
    category = models.CharField(max_length=100)
    number = models.IntegerField(default=0)
    

    

    def __str__(self):
        return self.title

3. 
![스크린샷 2023-03-27 160512](https://user-images.githubusercontent.com/127607342/227866013-1b4db296-bb2a-4688-8100-5f8605825018.png)
![스크린샷 2023-03-27 160617](https://user-images.githubusercontent.com/127607342/227866039-ec684921-9358-4b08-b262-691ec197c65b.png)

4. https://github.com/anj1nkyu/4session

**Comment by LinQuixote** [comment]
1. 이인
2. <img width="1423" alt="스크린샷 2023-03-27 오후 4 06 44" src="https://user-images.githubusercontent.com/96329698/227866849-ef35bbe1-0ee8-4859-a16d-884e1a248945.png">
3. ![Uploading 스크린샷 2023-03-27 오후 4.06.44.png…]()
4. https://github.com/LinQuixote/session4

**Comment by minsun24** [comment]
1. 정민선
2.
`from django.db import models
from django.utils import timezone  # timezone 모듈 불러오기



# Create your models here.
# 블로그
class Blog(models.Model):
      title = models.CharField(max_length=100)
      ages = models.IntegerField(default=20)
      # Student_ = [('FR','Freshman'),('SO','Sophomore'),('JR','Junior'),('SR','Senior')]
      # student_grade = models.CharField(choices = Student_, max_length=2, null =True)
      Email = models.EmailField(max_length=200) 
      created_at = models.DateTimeField(auto_now_add=True)
      contents = models.TextField() # 글자수에 제한 없는 텍스트
      
    #인스턴스 보이는 이름 바꾸기 
      def __str__(self):
            return self.title`
3.
![image](https://user-images.githubusercontent.com/122660256/227881896-7ad64e25-28cc-40eb-9786-b377ed3ed5b0.png)
![image](https://user-images.githubusercontent.com/122660256/227881989-7703ba06-45b4-4935-b1f1-1f9803d1e174.png)

**Comment by Muon05** [comment]
1. 송보경
2. 
``` python
class Blog(models.Model):
    title = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    introduce = models.TextField()
    url = models.URLField(null=True)
    email = models.EmailField(max_length = 60, null=True)

    def __str__(self):
        return self.title
```
3. 
![이얍](https://user-images.githubusercontent.com/127873267/227892271-e7776583-d25b-438e-8e47-a4b23adc211d.PNG)

4. https://github.com/Muon05/Muon.git

**Comment by kangmingi20223160** [comment]
1. 강민기
2. from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    introduce = models.TextField()
    created_by = models.CharField(max_length=18)
    
    def __str__(self):
        return self.title
        
3.
![스크린샷(21)](https://user-images.githubusercontent.com/113087740/227893217-0229d009-6db3-439e-853a-f6513b0ddfac.png)

4.https://github.com/kangmingi20223160/session4

**Comment by mumat0103** [comment]
마감

**Comment by haedawn** [comment]
1.양정민
`2.`from django.db import models

# Create your models herce.
class Blog(models.Model):
    title = models.CharField(max_length=100)
    created_at=models.DateTimeField(auto_now_add=True)
    introduce = models.TextField()
    content=models.TextField()


    def __str__(self):
        return self.title
    
    def summary(self):
        return self.content[:100]``

3.
<img width="1422" alt="스크린샷 2023-03-27 오후 10 01 03" src="https://user-images.githubusercontent.com/127366242/227946437-76612420-94fa-4945-9864-9150229f732d.png">
4. https://github.com/haedawn/blog_assignment.git

**Comment by koomchang** [comment]
전원 제출 완료
